### ISSUE TITLE
Performance Plugin Configuration Too Late

### ISSUE THREAD

**Issue by JakeWharton** [nebula-plugins/gradle-rxjava-project-plugin#7]
The perf plugin adding dependencies to the project based on the presence of the `JavaPlugin` is no longer allowed.

Seeing this with Gradle 2.2.1. Technically it's not blocking us (RxAndroid) since the resolution of #6 (an actual blocker) will prevent this code from ever being run, but others may experience it.

https://github.com/nebula-plugins/gradle-rxjava-project-plugin/blob/58308e13356c4d0185aa07e054f8c988fb9561c0/src/main/groovy/nebula/plugin/rxjavaproject/RxjavaPerformancePlugin.groovy#L33-L36

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change configuration ':rxandroid:perfCompile' after it has been resolved.
    at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:401)
    at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$400(DefaultConfiguration.java:46)
    at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$VetoContainerChangeAction.run(DefaultConfiguration.java:504)
    at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:259)
    at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
    at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:80)
    at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.doAdd(DefaultDependencyHandler.java:84)
    at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.methodMissing(DefaultDependencyHandler.java:119)
    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:163)
    at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated.invokeMethod(Unknown Source)
    at nebula.plugin.rxjavaproject.RxjavaPerformancePlugin$_apply_closure1_closure2.doCall(RxjavaPerformancePlugin.groovy:34)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
    at org.gradle.api.internal.project.AbstractProject.dependencies(AbstractProject.java:843)
    at org.gradle.api.Project$dependencies$9.call(Unknown Source)
    at nebula.plugin.rxjavaproject.RxjavaPerformancePlugin$_apply_closure1.doCall(RxjavaPerformancePlugin.groovy:33)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
    at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:203)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
    at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
    at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
    at nebula.plugin.rxjavaproject.RxjavaPerformancePlugin.apply(RxjavaPerformancePlugin.groovy:27)
    at nebula.plugin.rxjavaproject.RxjavaPerformancePlugin.apply(RxjavaPerformancePlugin.groovy)
    at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
    at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
    at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:107)
    at org.gradle.api.plugins.PluginContainer$apply.call(Unknown Source)
    at nebula.plugin.rxjavaproject.RxjavaProjectPlugin.apply(RxjavaProjectPlugin.groovy:121)
    at nebula.plugin.rxjavaproject.RxjavaProjectPlugin.apply(RxjavaProjectPlugin.groovy)
    at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
    at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
    at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
    ... 52 more
```

**Comment by quidryan** [comment]
I see #6 merged and the project's gone to 2.2.1. I checked out the project and was able to run it with 2.2.1. Is this still an issue? How were you seeing it?
